apiVersion: v1
kind: Service
metadata:
  labels:
    app: meshlab-data-svc
  name: meshlab-data-svc
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: meshlab-data-svc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: meshlab-data-svc
  name: meshlab-data-svc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: meshlab-data-svc
  template:
    metadata:
      labels:
        app: meshlab-data-svc
    spec:
      containers:
      - image: quay.io/lander2k2/meshlab_data_svc:0.1
        name: meshlab-data-svc
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
      restartPolicy: Always

