#
# https://istio.io/docs/tasks/policy-enforcement/rate-limiting/
#
apiVersion: config.istio.io/v1alpha2
kind: memquota
metadata:
  name: handler
  namespace: istio-system
spec:
  quotas:
  - name: requestcount.quota.istio-system
    maxAmount: 50
    validDuration: 1s
    overrides:
    - dimensions:
        source: meshlab-ui
        destination: meshlab-rate-limit-data-svc
      maxAmount: 1
      validDuration: 3s
---
apiVersion: config.istio.io/v1alpha2
kind: quota
metadata:
  name: requestcount
  namespace: istio-system
spec:
  dimensions:
    source: source.labels["app"] | source.service | "unknown"
    destination: destination.labels["app"] | destination.service | "unknown"
---
apiVersion: config.istio.io/v1alpha2
kind: rule
metadata:
  name: quota
  namespace: istio-system
spec:
  actions:
  - handler: handler.memquota
    instances:
    - requestcount.quota
---
apiVersion: config.istio.io/v1alpha2
kind: QuotaSpec
metadata:
  name: request-count
  namespace: istio-system
spec:
  rules:
  - quotas:
    - charge: "1"
      quota: requestcount
---
apiVersion: config.istio.io/v1alpha2
kind: QuotaSpecBinding
metadata:
  name: request-count
  namespace: istio-system
spec:
  quotaSpecs:
  - name: request-count
    namespace: istio-system
  services:
  - name: meshlab-ui
    namespace: default
  - name: meshlab-rate-limit-data-svc
    namespace: default
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: meshlab-rate-limit-data-svc
    version: v1
  name: meshlab-rate-limit-data-svc
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: meshlab-rate-limit-data-svc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: meshlab-rate-limit-data-svc
  name: meshlab-rate-limit-data-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meshlab-rate-limit-data-svc
  template:
    metadata:
      labels:
        app: meshlab-rate-limit-data-svc
    spec:
      containers:
      - image: quay.io/lander2k2/meshlab_data_svc:0.1
        name: rate-limit-data-svc
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
      restartPolicy: Always

